### ISSUE TITLE
Thing Cleanup

### ISSUE THREAD

**Issue by calderonroberto** [ubc-magic/thingbroker#18]
- Things should have an "expire" or "lifespan" field.
- The thingbroker should timestamp when a thing is touched by an app (get events, post events, follow a thing, etc).
- There should be a cleanup worker that unfollows and deletes all things that have gone bad (past their expire date).

**Comment by mblackstock** [comment]
We need to have a  last_accessed timestamp and an expiry time field. When
the thing expires the thingbroker can clean it up.

**Comment by mblackstock** [comment]
The use case for this is temporary things or things that an application can't or won't manage its life cycle. With an expiry time apps can create things knowing they will go away if forgotten after some period of time.
