### ISSUE TITLE
long polling real time event streams need 'per-application' queues

### ISSUE THREAD

**Issue by mblackstock** [ubc-magic/thingbroker#21]
Currently each thing has only one real time event queue.  If multiple ThB clients (applications) retrieve real time events on a thing, they will not get all events since they compete with other clients (applications) retrieving events on the same queue.

To work around this, we suggested creating new things that represent the application clients themselves, however, this means the app/client thing needs to follow all of the things that the target thing is following, otherwise it will not get events from target-followed things.  (We probably need a diagram to illustrate this, not sure it is clear).

To address the above issues, we will create a new application resource to represent ThB clients.  There will be a queue per application-thing rather than a queue per thing.

This way multiple apps can get real time events on a thing without the possibility of missing events since they will no longer share the same real time event queue.  There will be no need to create new things to effectively create new real time queues.  

Note that it will be important that current applications continue to work as expected (i.e. RED).  For backward compatibility we can create and use a default application queue for a thing if the application is not specified.

This will require CRUD application resources, and a way to get events for a specified application.

POST /applications - create an application, return created application with its id.
GET /applications - get all of the applications
DELETE /applications/{appId} - delete the specified application by id
PUT /applications/{appId} - update the application by id

An application representation (as simple as possible):
    {
        "_id": 123456,
        "name": "app name"
    }

To retrieve events:

GET /things/{thingId}/events?app=123456

This would retrieve events for only application (client) 123456.  Other clients long polling on the thing would not be affected assuming they supply their own application id.

For backward compatibility a default application will be used when none is supplied.

**Comment by calderonroberto** [comment]
I'm trying to wrap my head around this too. What happens when an application has different instances. For example, when the same app is deployed in two different large display containers, and accessed simultaneously by two applications? Won't these two compete for the same queue? Then each time a new instance of the app is registered, the plugin will have to not only create "clones" of things, but also clones of "applications" right? This seems a bit of overhead.

**Comment by mblackstock** [comment]
The management framework (in this case RED probably) probably needs to manage the applications and things that are created and deleted as it does now.  You would likely need to create a Thing Broker 'application' resource for every RED application (only one) so that all of its components have their own Thing Broker event queues.

**Comment by mblackstock** [comment]
Roberto: This is why I don't like the following solution and even application - centred queue. What should happen is that tb should have a list of clients pulling on a thing id and deliver to all of them. Or that when an event is received tb looks for long pulling requests and delivers parallel to all of them.

Yes, my thinking is that applications ARE clients of the ThB, and the ThB would maintain a list of all created applications (clients).  The assumption is that the apps register themselves, get an id and use their ids when polling.  The ThB would send real time events to all of the per-application queues that are doing long polling on a given thing.

The way its done now is when any app does long polling, we create a single shared event queue in RAM for the thing.  I'm suggesting that when an app does long polling, it identifies itself (i.e. with its client/app id as I suggest) and we create a queue for just that client/app.  There will be as many queues as there are apps long polling on the thing.

Do you think that will do it?

**Comment by mblackstock** [comment]
Another alternative (used in the REST broker 1) was to have a single queue per application (was called a clientId).  Applications would subscribe to channels (things) and events from all things would go to that single queue.

In the current ThB, we now have "following/follower" relationships which allows a single thing to aggregate events from multiple things so I don't see the need.

Future versions of the ThB could support per-application streams that get the events from _all_ of the things (and potentially the things they are following) if needed.

**Comment by mblackstock** [comment]
Added new "application" object as described, added new parameter to event call "appId".  If supplied, we create another queue for real time events specific to the app and the thing, hashing on {appId}:{thingId} string rather than just {thingId}.  Tested all controllers.  Need to update documentation.  Will open another issue.
