### ISSUE TITLE
move documentation to wiki

### ISSUE THREAD

**Issue by mblackstock** [ubc-magic/thingbroker#3]
Move API documentation to the github wiki, or a doc folder, not README

**Comment by calderonroberto** [comment]
Documentation should be both on the wiki and the readme file. So that
people can see it when they visit the site

**Comment by mblackstock** [comment]
Agreed - I'll put a link to the documentation on the README.

On Wed, Jan 30, 2013 at 3:57 PM, calderonroberto
notifications@github.comwrote:

> Documentation should be both on the wiki and the readme file. So that
> people can see it when they visit the site
> On Jan 30, 2013 3:47 PM, "Mike Blackstock" notifications@github.com
> wrote:
> 
> > Move API documentation to the github wiki, or a doc folder, not README
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/ubc-magic/thingbroker/issues/3>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ubc-magic/thingbroker/issues/3#issuecomment-12919824.

## 

MAGIC – Media and Graphics Interdisciplinary Centre
FSC 3640 – 2424 Main Mall | Vancouver BC | V6T 1Z4
mblackst@magic.ubc.ca | lab: 604-822-9248 | cell: 604-760-9035
