### ISSUE TITLE
support getting events sent only directly to a thing

### ISSUE THREAD

**Issue by mblackstock** [ubc-magic/thingbroker#30]
some use cases require getting events only sent directly to a thing, not to the things it is following

**Comment by mblackstock** [comment]
Done.

getting events, i.e. 

GET /things/{thing-id}/events

now supports a "filter" query parameter where the value can be

filter=all - get all events, both sent directly to the thing, as well as the things it is following
filter=thing-only - get events sent directly to the thing
filter=following-only - get events sent to the things the target thing is following.

**Comment by calderonroberto** [comment]
is this parameter required? will calling the GET /things/{thing-id}/events
return "filter=all" by default?

**Comment by mblackstock** [comment]
Yes, its documented on the wiki - 'all' is the default.  I left the 'followingOnly' flag support in the code for backward compatibility in case you were depending on it.
